### ISSUE TITLE
CWつきトゥートの内容だけが表示される

### ISSUE THREAD

**Issue by kagurazakarasen** [byusnco/favdon#14]
CWを付けて内容を隠したトゥートでも内容のみが表示されて、逆にタイトルが表示されていないようです。

https://favdon.herokuapp.com/users/21
↑参考
（CWを使って小説を投稿していますが、タイトルが出ず）

**Comment by foloinfo** [comment]
"spoiler_text": 内にCWのタイトルが入るみたいですね。
Mastodonと同様に隠しておいて、ユーザーの判断で続きを読むか選択出来た方が良さそうです。
修正しますー。
